from __future__ import annotations

import os
import platform as _platform
import shlex
import stat
from pathlib import Path
from typing import Any, List, Mapping, Optional

from platformdirs import user_config_dir
from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, DotEnvSettingsSource, SettingsConfigDict


APP_NAME = "viki-code"
APP_AUTHOR = "Rebootix"
USER_CONFIG_FILENAME = "config.env"


def user_config_root() -> Path:
    override = os.environ.get("VIKI_CONFIG_HOME", "").strip()
    if override:
        return Path(override).expanduser().resolve()
    return Path(user_config_dir(APP_NAME, APP_AUTHOR)).resolve()


def user_config_path() -> Path:
    return user_config_root() / USER_CONFIG_FILENAME


class VikiDotEnvSettingsSource(DotEnvSettingsSource):
    def __init__(self, settings_cls: type[BaseSettings]) -> None:
        super().__init__(
            settings_cls,
            env_file=(str(user_config_path()), ".env"),
            env_file_encoding="utf-8",
        )


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    parsed: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        parsed[key] = value
    return parsed


def _serialize_env_file(values: Mapping[str, str]) -> str:
    lines = [
        "# VIKI Code user configuration",
        "# Generated by the guided setup flow.",
        "",
    ]
    for key in sorted(values):
        value = values[key]
        if value is None:
            continue
        needs_quotes = any(ch.isspace() for ch in value) or any(ch in value for ch in ['"', "'", "#"])
        rendered = shlex.quote(value) if needs_quotes else value
        lines.append(f"{key}={rendered}")
    lines.append("")
    return "\n".join(lines)


def _apply_file_mode(path: Path) -> None:
    try:
        if os.name != "nt":
            path.chmod(stat.S_IRUSR | stat.S_IWUSR)
        else:
            os.chmod(path, stat.S_IREAD | stat.S_IWRITE)
    except OSError:
        pass


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file_encoding="utf-8", extra="ignore")

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: Any,
        env_settings: Any,
        dotenv_settings: Any,
        file_secret_settings: Any,
    ):
        return (
            init_settings,
            env_settings,
            VikiDotEnvSettingsSource(settings_cls),
            file_secret_settings,
        )

    viki_provider: Optional[str] = Field(default=None, alias="VIKI_PROVIDER")
    viki_provider_allow_fallbacks: bool = Field(default=False, alias="VIKI_PROVIDER_ALLOW_FALLBACKS")
    viki_theme: str = Field(default="premium", alias="VIKI_THEME")
    default_run_mode: str = Field(default="standard", alias="VIKI_DEFAULT_RUN_MODE")
    openrouter_api_key: Optional[str] = None
    openai_api_key: Optional[str] = None
    dashscope_api_key: Optional[str] = None
    nvidia_api_key: Optional[str] = None
    nvidia_api_base: Optional[str] = None
    anthropic_api_key: Optional[str] = None
    google_api_key: Optional[str] = None
    deepseek_api_key: Optional[str] = None
    groq_api_key: Optional[str] = None
    mistral_api_key: Optional[str] = None
    togetherai_api_key: Optional[str] = None
    fireworks_api_key: Optional[str] = None
    xai_api_key: Optional[str] = None
    cerebras_api_key: Optional[str] = None
    sambanova_api_key: Optional[str] = None
    azure_api_key: Optional[str] = None
    azure_api_base: Optional[str] = None
    azure_api_version: Optional[str] = None
    openai_api_base: Optional[str] = None
    dashscope_api_base: str = "https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
    openrouter_api_base: str = "https://openrouter.ai/api/v1"
    ollama_base_url: Optional[str] = None
    ollama_model: Optional[str] = None

    reasoning_model: str = "reasoning"
    coding_model: str = "coding"
    quick_model: str = "fast"
    local_model: str = "ollama/qwen2.5-coder:7b"

    max_cost_per_task_usd: float = 10.0
    max_tokens_per_task: int = 120000
    max_api_calls_per_minute: int = 40
    enable_cost_tracking: bool = True

    sandbox_enabled: bool = True
    sandbox_network_enabled: bool = False
    sandbox_worktree_only: bool = True
    docker_image: str = "viki-sandbox:latest"
    sandbox_memory_limit: str = "2g"
    sandbox_nano_cpus: int = 2000000000
    sandbox_pids_limit: int = 256
    max_execution_time_seconds: int = 300
    max_repair_attempts: int = 2
    approval_mode: str = "auto"
    approval_session_grants_enabled: bool = True
    approval_risk_threshold: int = 50
    high_risk_command_tokens: List[str] = Field(default_factory=lambda: [
        "git push", "gh pr create", "docker push", "kubectl apply", "terraform apply", "rm -rf", "chmod 777",
    ])
    forbidden_modules: List[str] = Field(default_factory=lambda: [
        r"os\.system",
        r"subprocess\.Popen",
        r"socket\.",
        r"requests\.(get|post|put|delete)",
    ])
    secret_patterns: List[str] = Field(default_factory=lambda: ["sk-", "AKIA", "ghp_", "private_key"])
    allowed_command_prefixes: List[str] = Field(default_factory=lambda: [
        "python", "python3", "pytest", "pip", "uv", "poetry", "ruff", "mypy",
        "npm", "pnpm", "yarn", "bun", "node", "npx",
        "cargo", "go", "javac", "java", "gradle", "./gradlew",
        "make", "cmake", "ctest", "git", "bash", "sh", "pwsh", "powershell",
    ])

    max_swarm_depth: int = 3
    max_agents_per_swarm: int = 5
    max_parallel_swarms: int = 8
    enable_fractal_recursion: bool = True
    context_budget_chars: int = 18000
    route_large_repo_threshold: int = 250

    database_url: str = "sqlite:///./.viki-workspace/viki.db"
    checkpoint_interval_seconds: int = 20
    session_timeout_hours: int = 24

    workspace_dir: str = ".viki-workspace"
    sandbox_dir: str = ".viki-workspace/sandbox"
    memory_dir: str = ".viki-workspace/memory"
    log_dir: str = ".viki-workspace/logs"
    temp_dir: str = ".viki-workspace/temp"
    skill_dir: str = ".viki-workspace/skills"
    runs_dir: str = ".viki-workspace/runs"
    benchmark_dir: str = ".viki-workspace/benchmarks"
    skill_env_dir: str = ".viki-workspace/skill_envs"
    skill_manifest_name: str = "manifest.yaml"

    log_level: str = "INFO"
    metrics_enabled: bool = True
    metrics_port: int = 9090
    structured_logging: bool = True

    api_host: str = "127.0.0.1"
    api_port: int = 8787


    telegram_enabled: bool = False
    telegram_bot_token: Optional[str] = None
    telegram_webhook_secret: Optional[str] = None
    telegram_allowed_chat_ids: str = ""
    telegram_reply_max_chars: int = 3500

    whatsapp_enabled: bool = False
    whatsapp_account_sid: Optional[str] = None
    whatsapp_auth_token: Optional[str] = None
    whatsapp_from_number: Optional[str] = None
    whatsapp_allowed_senders: str = ""
    whatsapp_validate_signature: bool = True
    whatsapp_webhook_url: Optional[str] = None
    whatsapp_reply_max_chars: int = 3000

    platform: str = Field(default_factory=lambda: _platform.system().lower())
    shell_path: Optional[str] = None

    @field_validator("shell_path", mode="before")
    @classmethod
    def set_shell(cls, value: Optional[str]) -> str:
        if value:
            return value
        return "powershell.exe" if _platform.system().lower().startswith("win") else "/bin/bash"

    def ensure_workspace(self, root: str | Path = ".") -> Path:
        root_path = Path(root).resolve()
        workspace = root_path / self.workspace_dir
        for relative in [
            self.workspace_dir,
            self.sandbox_dir,
            self.memory_dir,
            self.log_dir,
            self.temp_dir,
            self.skill_dir,
            self.runs_dir,
            self.benchmark_dir,
            self.skill_env_dir,
        ]:
            (root_path / relative).mkdir(parents=True, exist_ok=True)
        return workspace


settings = Settings()


def refresh_settings() -> Settings:
    fresh = Settings()
    for field_name in Settings.model_fields:
        setattr(settings, field_name, getattr(fresh, field_name))
    return settings


def write_user_config(values: Mapping[str, Optional[str]], *, remove_empty: bool = True) -> Path:
    root = user_config_root()
    root.mkdir(parents=True, exist_ok=True)
    config_file = user_config_path()
    existing = _parse_env_file(config_file)

    merged = dict(existing)
    for key, value in values.items():
        if value is None and remove_empty:
            merged.pop(key, None)
            continue
        if value is None:
            continue
        merged[key] = str(value)

    tmp_path = config_file.with_suffix(".tmp")
    tmp_path.write_text(_serialize_env_file(merged), encoding="utf-8")
    _apply_file_mode(tmp_path)
    tmp_path.replace(config_file)
    _apply_file_mode(config_file)
    refresh_settings()
    return config_file


def read_user_config() -> dict[str, str]:
    return _parse_env_file(user_config_path())
